apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ca.crt: "{{ .Values.matchbox.ssl.ca }}"
  server.crt: "{{ .Values.matchbox.ssl.crt }}"
  server.key: "{{ .Values.matchbox.ssl.key }}"
