apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: matchbox
spec:
  rules:
    - host: matchbox.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: matchbox-rpc
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
        - matchbox-rpc.example.com
  rules:
    - host: matchbox-rpc.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8081
